/*
 * PulseCode.h *  Created on: 22.04.2013 *      Author: H.Bani */

#ifndef PULSECODE_H_
#define PULSECODE_H_

/**
 * Pulse Code der Generiert wird falls eine Input Änderung stattfindet
 */namespace hal{
enum PulseCode{	PULSE_SENSORIK_START,					//0
	//Tasten
	PULSE_TASTE_START_IST_GEDRUECKT,		//1
	PULSE_TASTE_START_IST_NICHT_GEDRUECKT , //2
	PULSE_TASTE_STOP_IST_GEDRUECKT ,		//3
	PULSE_TASTE_RESET_IST_GEDRUECKT,		//4
	PULSE_TASTE_RESET_IST_NICHT_GEDRUECKT ,	//5
	PULSE_TASTE_EMERGENCY,					//6	PULSE_TASTE_EMERGENCY_NICHT_GEDRUEKT,	//7
	//Werkstück
	PULSE_WERKSTUECK_IN_HOEHENMESSUNG,		//8
	PULSE_WERKSTUECK_NICHT_IN_HOEHENMESSUNG,//9	PULSE_WERKSTUECK_ZU_FLACH,				//10
	PULSE_WERKSTUECK_IN_Toleranzbereich,	//11
	PULSE_WERKSTUECK_METAL,					//12
	PULSE_WERKSTUECK_IM_EINLAUF,			//13
	PULSE_WERKSTUECK_NICHT_IM_EINLAUF,		//14
	PULSE_WERKSTUECK_IM_AUSLAUF,			//15
	PULSE_WERKSTUECK_NICHT_IM_AUSLAUF,		//16
	PULSE_WERKSTUECK_NICHT_IN_WEICHE,		//17
	PULSE_WERKSTUECK_IN_WEICHE,				//18
	//Weiche
	PULSE_WEICHE_IST_OFFEN,					//19
	//Rutsche
	PULSE_RUTSCHE_SCHRANKE_FREI,			//20	PULSE_RUTSCHE__SCHRANKE_GESPERRT,		//21	//Uebergabe	PULSE_UEBERGABE_MIT_BOHRUNG,			//22	PULSE_UEBERGABE_OHNE_BOHRUNG,			//23
	//Fehler	PULSE_FEHLER_WURDE_QUITTIERT,			//24	PULSE_WK_VERSCHWUNDEN,					//25	PULSE_WK_NEUAUFGETAUCHT,				//26	PULSE_WK_NICHT_UMGEDREHT,				//27	PULSE_RUTSCHE_IST_VOLL,					//28	PULSE_WEICHE_IST_VERKLEMMT,				//29	PULSE_BANDSTOPP_FEHLERMELDUNG,			//30	PULSE_UEBERGABE_FEHLERMELDUNG,			//31	//Timer	PULSE_TIME,								//32	WK_TIMEOUT,								//33	SYNC_TIME_STOPP,						//34	SYNC_TIME_FREE,							//35	//Synchronisation	//Uebergabe	SYNC_IS_B2EMPTY,						//36	SYNC_NOTIFY_EMPTY,						//37	SYNC_NOTIFY_WK_AUFB2,					//38	SYNC_UEBERGABE_TIMEOUT,					//39	SYNC_MOTOR2_STARTEN,					//40	//Estopp	SYNC_ESTOPP_GEDRUECKT,					//41	SYNC_ESTOPP_LOS,						//42	//Dispatcher	PULSE_STOPP_DISPATCHER,	PULSE_FREE_DISPATCHER,	NOTHING,								//43	PULSE_END
};
}

#endif /* PULSECODE_H_ */
